angular.module('CareChat').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/chats.html',
    "<div class=\"main\" ng-init=\"init()\"> <div class=\"chats\"> <div class=\"btn-group\" ng-show=\"profile.admin\"><button type=\"button\" class=\"btn\" ng-class=\"{'btn-primary':sort==undefined,'btn-default':sort!==undefined}\" ng-click=\"sort=undefined\">All</button><button type=\"button\" class=\"btn\" ng-class=\"{'btn-primary':sort===true,'btn-default':sort!==true}\" ng-click=\"sort=true\">Administrators</button><button type=\"button\" class=\"btn\" ng-class=\"{'btn-primary':sort===false,'btn-default':sort!==false}\" ng-click=\"sort=false\">Users</button></div> <ul class=\"list-group chat-list margin-top-15\"> <li class=\"list-group-item chat-item\" ng-repeat=\"sender in senders | filter:{admin:sort} | orderBy:'name'\"> <div class=\"chat-header\" ng-click=\"chatBox(sender)\"><label>{{sender.name}}</label><div class=\"status\" ng-class=\"{'online':users[sender.uid].online,'offline':!users[sender.uid].online}\"></div><span class=\"pull-right badge\" ng-show=\"sender.unread\">{{sender.unread}}</span></div> <div class=\"chat-body collapse\" ng-class=\"{'in':sender.inbox}\"> <div class=\"chat-messages margin-top-15 margin-bottom-20\"> <ul class=\"list-group\"> <li class=\"list-group-item\" ng-class=\"{'user':chat.sid === user.uid,'sender':chat.sid !== user.uid}\" ng-repeat=\"chat in sender.chats\">{{chat.msg}}</li> </ul> </div> <div class=\"chat-input\"> <form class=\"form\" name=\"ChatForm\"> <div class=\"form-group\"> <input type=\"text\" name=\"InputMessage\" ng-model=\"sender.reply\" ng-keypress=\"sendWithEnter($event,sender,user.uid)\" autofocus class=\"form-control\"> </div> <div class=\"form-group\"> <div class=\"text-right\"> <button type=\"button\" ng-click=\"clear(sender)\" class=\"btn btn-default margin-right-10\">Clear</button> <button type=\"button\" ng-click=\"send(sender,user.uid)\" class=\"btn btn-success\">Reply</button> </div> </div> </form> </div> </div> </li> </ul> </div> </div>"
  );


  $templateCache.put('views/dashboard.html',
    "<div ng-init=\"init()\"> Welcome, <b>{{profile.name}}</b> <br> This is a demo chat app based on angular and firebase. <br> You logged in as <b>{{profile.admin?'Administrator':'User'}}</b>. <br> Please go to chats section of this app to enjoy chatting experience. <br> <b>Note:</b> Users can't chat with each other. </div>"
  );


  $templateCache.put('views/login.html',
    "<div class=\"main\" ng-init=\"init()\"> <form class=\"form\" name=\"loginForm\" ng-submit=\"submit(user)\"> <div class=\"form-group alert alert-danger\" ng-show=\"showError\"> <label class=\"\">{{errorMessage}}</label> <span ng-click=\"showError = false\" class=\"close\">X</span> </div> <div class=\"form-group\"> <label class=\"control-label\">Email</label> <div class=\"input-group\"> <input type=\"text\" class=\"form-control\" ng-model=\"user.email\"> <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span> </div> <br> <label class=\"control-label\">Password</label> <div class=\"input-group\"> <input type=\"password\" class=\"form-control\" ng-model=\"user.password\"> <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span> </div> <br> <div class=\"row\"> <div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-6\"> <button type=\"submit\" name=\"submit\" class=\"form-control btn btn-primary\">Login</button> </div> <div class=\"col-xs-12 hidden-sm hidden-md hidden-lg\"> <br> </div> <div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-6\"> <button type=\"button\" name=\"submit\" class=\"form-control btn btn-default\" ng-click=\"clear()\">Clear</button> </div> </div> <br> <div class=\"form-group\"> <label class=\"\">Need an account? &nbsp;<a href=\"#/register\">Register here</a></label> </div> </div> </form> </div>"
  );


  $templateCache.put('views/profile.html',
    "<div class=\"main margin-bottom-40\" ng-init=\"init()\"> <h3>Profile Settings</h3> <form name=\"ProfileForm\" class=\"form\" ng-submit=\"save()\"> <div class=\"form-group alert alert-danger\" ng-show=\"showError\"> <label class=\"\">{{errorMessage}}</label> <span ng-click=\"showError = false\" class=\"close\">X</span> </div> <div class=\"form-group alert alert-success\" ng-show=\"showSuccess\"> <label class=\"\">{{successMessage}}</label> <span ng-click=\"showSuccess = false\" class=\"close\">X</span> </div> <hr> <h5 class=\"text-muted\">Personal Information</h5> <div class=\"form-group\"> <label class=\"control-label\">Name</label> <input type=\"text\" ng-model=\"profile.name\" class=\"form-control\" name=\"Name\"> </div> <div class=\"form-group\"> <label class=\"control-label\">Age</label> <input type=\"text\" ng-model=\"profile.age\" class=\"form-control\" name=\"Age\"> </div> <div class=\"form-group\"> <label class=\"control-label\">Mobile</label> <input type=\"text\" ng-model=\"profile.mobile\" maxlength=\"10\" class=\"form-control\" name=\"Mobile\"> </div> <div class=\"form-group\"> <label class=\"control-label\">Email</label> <input type=\"text\" ng-model=\"profile.email\" disabled class=\"form-control\" name=\"Email\"> </div> <hr> <h5 class=\"text-muted\">Address Information</h5> <div class=\"form-group\"> <label class=\"control-label\">Line 1</label> <input type=\"text\" ng-model=\"profile.address.line1\" class=\"form-control\" name=\"Line1\"> </div> <div class=\"form-group\"> <label class=\"control-label\">Line 2</label> <input type=\"text\" ng-model=\"profile.address.line2\" class=\"form-control\" name=\"Line2\"> </div> <div class=\"form-group\"> <label class=\"control-label\">City</label> <input type=\"text\" ng-model=\"profile.address.city\" class=\"form-control\" name=\"City\"> </div> <div class=\"form-group\"> <label class=\"control-label\">State</label> <input type=\"text\" ng-model=\"profile.address.state\" class=\"form-control\" name=\"State\"> </div> <div class=\"form-group\"> <div class=\"pull-right\"> <div class=\"input-group\"> <button type=\"button\" name=\"Cancel\" ng-click=\"cancel()\" class=\"btn btn-default margin-right-10\">Cancel</button> <button type=\"submit\" name=\"Submit\" class=\"btn btn-success\">Save</button> </div> </div> </div> <br> </form> </div>"
  );


  $templateCache.put('views/register.html',
    "<div class=\"main\" ng-init=\"init()\"> <form class=\"form\" name=\"registerForm\" ng-submit=\"submit(user)\"> <div class=\"form-group alert alert-danger\" ng-show=\"showError\"> <label class=\"\">{{errorMessage}}</label> <span ng-click=\"showError = false\" class=\"close\">X</span> </div> <div class=\"form-group alert alert-success\" ng-show=\"showSuccess\"> <label class=\"\">{{successMessage}}</label> <span ng-click=\"showSuccess = false\" class=\"close\">X</span> </div> <div class=\"form-group\"> <label class=\"control-label\">Name</label> <div class=\"input-group\"> <input type=\"text\" class=\"form-control\" ng-model=\"user.name\"> <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span> </div> <br> <label class=\"control-label\">Email</label> <div class=\"input-group\"> <input type=\"text\" class=\"form-control\" ng-model=\"user.email\"> <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-inbox\"></i></span> </div> <br> <label class=\"control-label\">Password</label> <div class=\"input-group\"> <input type=\"password\" class=\"form-control\" ng-model=\"user.password\"> <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span> </div> <br> <label class=\"control-label\">Register as</label> <div class=\"input-group\"> <span class=\"radio-span\" ng-click=\"user.admin=true\"><input type=\"radio\" class=\"radio-inline role-radio\" ng-checked=\"user.admin\">Admin</span>&nbsp;&nbsp;&nbsp; <span class=\"radio-span\" ng-click=\"user.admin=false\"><input type=\"radio\" class=\"radio-inline role-radio\" ng-checked=\"!user.admin\">User</span> </div> <label class=\"margin-top-15 small text-info\" ng-show=\"!user.admin\">Note: User can't chat with each other.</label> <label class=\"margin-top-15 small text-info\" ng-show=\"user.admin\">Note: Admin will have all privileges, can chat with other admins as well as users.</label> <br> <br> <div class=\"row\"> <div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-6\"> <button type=\"submit\" name=\"submit\" class=\"form-control btn btn-primary\">Register</button> </div> <div class=\"col-xs-12 hidden-sm hidden-md hidden-lg\"> <br> </div> <div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-6\"> <button type=\"button\" name=\"submit\" class=\"form-control btn btn-default\" ng-click=\"clear()\">Clear</button> </div> </div> <br> <div class=\"form-group\"> <label class=\"\">Already have an account? &nbsp;<a href=\"#/\">Login here</a></label> </div> </div> </form> </div>"
  );

}]);
